# Generated by Django 4.0.4 on 2022-06-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del tipo')),
                ('nombreTipo', models.CharField(max_length=20, verbose_name='Nombre del tipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='url',
        ),
        migrations.AddField(
            model_name='auto',
            name='datoA',
            field=models.TextField(null=True, verbose_name='Descripcion auto 1'),
        ),
        migrations.AddField(
            model_name='auto',
            name='datoB',
            field=models.TextField(null=True, verbose_name='Descripcion auto 2'),
        ),
        migrations.AddField(
            model_name='auto',
            name='galeria1',
            field=models.ImageField(blank=True, null=True, upload_to='Galeria1'),
        ),
        migrations.AddField(
            model_name='auto',
            name='galeria2',
            field=models.ImageField(blank=True, null=True, upload_to='Galeria2'),
        ),
        migrations.AddField(
            model_name='auto',
            name='galeria3',
            field=models.ImageField(blank=True, null=True, upload_to='Galeria3'),
        ),
        migrations.AddField(
            model_name='auto',
            name='galeria4',
            field=models.ImageField(blank=True, null=True, upload_to='Galeria4'),
        ),
        migrations.AddField(
            model_name='auto',
            name='galeria5',
            field=models.ImageField(blank=True, null=True, upload_to='Galeria5'),
        ),
        migrations.AddField(
            model_name='auto',
            name='galeria6',
            field=models.ImageField(blank=True, null=True, upload_to='Galeria6'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Modelo'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='imagen especificacion1'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='imagen especificacion2'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='imagen especificacion3'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='imagen especificacion4'),
        ),
        migrations.AddField(
            model_name='auto',
            name='texto1',
            field=models.CharField(max_length=40, null=True, verbose_name='especificaciones1'),
        ),
        migrations.AddField(
            model_name='auto',
            name='texto2',
            field=models.CharField(max_length=40, null=True, verbose_name='especificaciones2'),
        ),
        migrations.AddField(
            model_name='auto',
            name='texto3',
            field=models.CharField(max_length=40, null=True, verbose_name='especificaciones3'),
        ),
        migrations.AddField(
            model_name='auto',
            name='texto4',
            field=models.CharField(max_length=40, null=True, verbose_name='especificaciones4'),
        ),
        migrations.AddField(
            model_name='auto',
            name='videoUrl',
            field=models.URLField(max_length=280, null=True, verbose_name='Url video'),
        ),
        migrations.AddField(
            model_name='auto',
            name='idtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo'),
        ),
    ]
