# Generated by Django 4.0.4 on 2022-06-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipo_delete_comentario_delete_rol_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='idtipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
