# Generated by Django 4.0.4 on 2022-06-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_auto_idtipo_delete_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='videoUrl',
            field=models.CharField(max_length=280, null=True, verbose_name='Url video'),
        ),
    ]
